# Generated by Django 6.0.7 on 2026-07-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(max_length=500)),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_overlays', to='graph.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'edge_id')},
            },
        ),
        migrations.CreateModel(
            name='NodeOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('system', 'System'), ('container', 'Container'), ('component', 'Component'), ('person', 'Person'), ('external', 'External')], max_length=20)),
                ('system_name', models.CharField(blank=True, default='', max_length=255)),
                ('container_name', models.CharField(blank=True, default='', max_length=255)),
                ('node_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_overlays', to='graph.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'node_type', 'system_name', 'container_name', 'node_name')},
            },
        ),
    ]
