# Generated by Django 6.0.7 on 2026-08-16 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_rename_workspace_projectmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexiconEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexicon_entries', to='graph.projectmap')),
            ],
            options={
                'unique_together': {('project_map', 'term')},
            },
        ),
    ]
