# Generated by Django 6.1 on 2026-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_projectmap_owner_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmap',
            name='github_branch',
            field=models.CharField(blank=True, default='main', max_length=255),
        ),
        migrations.AddField(
            model_name='projectmap',
            name='github_repo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
