# Generated by Django 6.1 on 2026-08-18 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_github_import_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='graph.projectmap')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accesses', to=settings.AUTH_USER_MODEL)),
                ('share_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='graph.sharetoken')),
            ],
            options={
                'unique_together': {('share_token', 'user')},
            },
        ),
    ]
