# Generated by Django 6.1 on 2026-08-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeoverlay',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
