# Generated by Django 6.1 on 2026-09-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_githubappinstallation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmap',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
